version: "3.9"
services:
  peer_master:
    image: hornet-ebsi
    stop_grace_period: 1m
    environment:
      - COO_PRV_KEYS=651941eddb3e68cb1f6ef4ef5b04625dcf5c70de1fdc4b1c9eadb2c219c074e0ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c,0e324c6ff069f31890d496e9004636fd73d8e8b5bea08ec58a4178ca85462325f6752f5f46a53364e2ee9c4d662d762a81efd51010282a75cd6bd03f28ef349c
      - FAUCET_PRV_KEY=52d23081a626b1eca34b63f1eaeeafcbd66bf545635befc12cd0f19926efefb031f176dadf38cdec0eadd1d571394be78f0bbee3ed594316678dffc162a095cb
    command: >
      --config=/run/secrets/hornet.config.json
      --cooBootstrap
      --cooStartIndex=0
      --protocol.networkID="private_tangle1"
      --restAPI.bindAddress="0.0.0.0:14265"
      --dashboard.bindAddress="0.0.0.0:8081"
      --db.path="privatedb"
      --node.disablePlugins="Autopeering"
      --node.enablePlugins="Spammer,Coordinator,MQTT,Debug,Prometheus,Faucet"
      --snapshots.fullPath=/tmp/snapshots/private_tangle1/full_snapshot.bin
      --snapshots.deltaPath="/tmp/snapshots/private_tangle1/delta_snapshot.bin"
      --p2p.bindMultiAddresses="/ip4/127.0.0.1/tcp/15600"
      --profiling.bindAddress="127.0.0.1:6060"
      --prometheus.bindAddress="localhost:9311"
      --prometheus.fileServiceDiscovery.target="localhost:9311"
      --mqtt.bindAddress="localhost:1883"
      --p2p.db.path="p2pstore"
      --p2p.identityPrivateKey="1f46fad4f538a031d4f87f490f6bca4319dfd0307636a5759a22b5e8874bd608f9156ba976a12918c16a481c38c88a7b5351b769adc30390e93b6c0a63b09b79"
      --p2p.peers="/ip4/127.0.0.1/tcp/15601/p2p/12D3KooWCKwcTWevoRKa2kEBputeGASvEBuDfRDSbe8t1DWugUmL,/ip4/127.0.0.1/tcp/15602/p2p/12D3KooWGdr8M5KX8KuKaXSiKfHJstdVnRkadYmupF7tFk2HrRoA,/ip4/127.0.0.1/tcp/15603/p2p/12D3KooWC7uE9w3RN4Vh1FJAZa8SbE8yMWR6wCVBajcWpyWguV73"
    secrets:
      - hornet.config.json
    volumes:
    - ./snapshots:/tmp/snapshots
    ports:
      - "8011:8081/tcp" # dashboard
      - "14165:14265/tcp" # REST-API
    networks:
      - shimmer
  peer_master2:
    image: hornet-ebsi
    stop_grace_period: 1m
    environment:
      - COO_PRV_KEYS=651941eddb3e68cb1f6ef4ef5b04625dcf5c70de1fdc4b1c9eadb2c219c074e0ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c,0e324c6ff069f31890d496e9004636fd73d8e8b5bea08ec58a4178ca85462325f6752f5f46a53364e2ee9c4d662d762a81efd51010282a75cd6bd03f28ef349c
      - FAUCET_PRV_KEY=52d23081a626b1eca34b63f1eaeeafcbd66bf545635befc12cd0f19926efefb031f176dadf38cdec0eadd1d571394be78f0bbee3ed594316678dffc162a095cb
    command: >
      --config=/run/secrets/hornet.config.json
      --cooBootstrap
      --cooStartIndex=0
      --protocol.networkID="private_tangle1"
      --restAPI.bindAddress="0.0.0.0:14265"
      --dashboard.bindAddress="0.0.0.0:8081"
      --db.path="privatedb"
      --node.disablePlugins="Autopeering"
      --node.enablePlugins="Spammer,Coordinator,MQTT,Debug,Prometheus,Faucet"
      --snapshots.fullPath=/tmp/snapshots/private_tangle2/full_snapshot.bin
      --snapshots.deltaPath="/tmp/snapshots/private_tangle2/delta_snapshot.bin"
      --p2p.bindMultiAddresses="/ip4/127.0.0.1/tcp/15600"
      --profiling.bindAddress="127.0.0.1:6060"
      --prometheus.bindAddress="localhost:9311"
      --prometheus.fileServiceDiscovery.target="localhost:9311"
      --mqtt.bindAddress="localhost:1883"
      --p2p.db.path="p2pstore"
      --p2p.identityPrivateKey="1f46fad4f538a031d4f87f490f6bca4319dfd0307636a5759a22b5e8874bd608f9156ba976a12918c16a481c38c88a7b5351b769adc30390e93b6c0a63b09b79"
      --p2p.peers="/ip4/127.0.0.1/tcp/15601/p2p/12D3KooWCKwcTWevoRKa2kEBputeGASvEBuDfRDSbe8t1DWugUmL,/ip4/127.0.0.1/tcp/15602/p2p/12D3KooWGdr8M5KX8KuKaXSiKfHJstdVnRkadYmupF7tFk2HrRoA,/ip4/127.0.0.1/tcp/15603/p2p/12D3KooWC7uE9w3RN4Vh1FJAZa8SbE8yMWR6wCVBajcWpyWguV73"
    secrets:
      - hornet.config.json
    volumes:
    - ./snapshots:/tmp/snapshots
    ports:
      - "8021:8081/tcp" # dashboard
      - "14265:14265/tcp" # REST-API
    networks:
      - shimmer
  peer_master3:
    image: hornet-ebsi
    stop_grace_period: 1m
    environment:
      - COO_PRV_KEYS=651941eddb3e68cb1f6ef4ef5b04625dcf5c70de1fdc4b1c9eadb2c219c074e0ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c,0e324c6ff069f31890d496e9004636fd73d8e8b5bea08ec58a4178ca85462325f6752f5f46a53364e2ee9c4d662d762a81efd51010282a75cd6bd03f28ef349c
      - FAUCET_PRV_KEY=52d23081a626b1eca34b63f1eaeeafcbd66bf545635befc12cd0f19926efefb031f176dadf38cdec0eadd1d571394be78f0bbee3ed594316678dffc162a095cb
    command: >
      --config=/run/secrets/hornet.config.json
      --cooBootstrap
      --cooStartIndex=0
      --protocol.networkID="private_tangle1"
      --restAPI.bindAddress="0.0.0.0:14265"
      --dashboard.bindAddress="0.0.0.0:8081"
      --db.path="privatedb"
      --node.disablePlugins="Autopeering"
      --node.enablePlugins="Spammer,Coordinator,MQTT,Debug,Prometheus,Faucet"
      --snapshots.fullPath=/tmp/snapshots/private_tangle3/full_snapshot.bin
      --snapshots.deltaPath="/tmp/snapshots/private_tangle3/delta_snapshot.bin"
      --p2p.bindMultiAddresses="/ip4/127.0.0.1/tcp/15600"
      --profiling.bindAddress="127.0.0.1:6060"
      --prometheus.bindAddress="localhost:9311"
      --prometheus.fileServiceDiscovery.target="localhost:9311"
      --mqtt.bindAddress="localhost:1883"
      --p2p.db.path="p2pstore"
      --p2p.identityPrivateKey="1f46fad4f538a031d4f87f490f6bca4319dfd0307636a5759a22b5e8874bd608f9156ba976a12918c16a481c38c88a7b5351b769adc30390e93b6c0a63b09b79"
      --p2p.peers="/ip4/127.0.0.1/tcp/15601/p2p/12D3KooWCKwcTWevoRKa2kEBputeGASvEBuDfRDSbe8t1DWugUmL,/ip4/127.0.0.1/tcp/15602/p2p/12D3KooWGdr8M5KX8KuKaXSiKfHJstdVnRkadYmupF7tFk2HrRoA,/ip4/127.0.0.1/tcp/15603/p2p/12D3KooWC7uE9w3RN4Vh1FJAZa8SbE8yMWR6wCVBajcWpyWguV73"
    secrets:
      - hornet.config.json
    volumes:
    - ./snapshots:/tmp/snapshots
    ports:
      - "8031:8081/tcp" # dashboard
      - "14365:14265/tcp" # REST-API
    networks:
      - shimmer
  peer_master4:
    image: hornet-ebsi
    stop_grace_period: 1m
    environment:
      - COO_PRV_KEYS=651941eddb3e68cb1f6ef4ef5b04625dcf5c70de1fdc4b1c9eadb2c219c074e0ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c,0e324c6ff069f31890d496e9004636fd73d8e8b5bea08ec58a4178ca85462325f6752f5f46a53364e2ee9c4d662d762a81efd51010282a75cd6bd03f28ef349c
      - FAUCET_PRV_KEY=52d23081a626b1eca34b63f1eaeeafcbd66bf545635befc12cd0f19926efefb031f176dadf38cdec0eadd1d571394be78f0bbee3ed594316678dffc162a095cb
    command: >
      --config=/run/secrets/hornet.config.json
      --cooBootstrap
      --cooStartIndex=0
      --protocol.networkID="private_tangle1"
      --restAPI.bindAddress="0.0.0.0:14265"
      --dashboard.bindAddress="0.0.0.0:8081"
      --db.path="privatedb"
      --node.disablePlugins="Autopeering"
      --node.enablePlugins="Spammer,Coordinator,MQTT,Debug,Prometheus,Faucet"
      --snapshots.fullPath=/tmp/snapshots/private_tangle4/full_snapshot.bin
      --snapshots.deltaPath="/tmp/snapshots/private_tangle4/delta_snapshot.bin"
      --p2p.bindMultiAddresses="/ip4/127.0.0.1/tcp/15600"
      --profiling.bindAddress="127.0.0.1:6060"
      --prometheus.bindAddress="localhost:9311"
      --prometheus.fileServiceDiscovery.target="localhost:9311"
      --mqtt.bindAddress="localhost:1883"
      --p2p.db.path="p2pstore"
      --p2p.identityPrivateKey="1f46fad4f538a031d4f87f490f6bca4319dfd0307636a5759a22b5e8874bd608f9156ba976a12918c16a481c38c88a7b5351b769adc30390e93b6c0a63b09b79"
      --p2p.peers="/ip4/127.0.0.1/tcp/15601/p2p/12D3KooWCKwcTWevoRKa2kEBputeGASvEBuDfRDSbe8t1DWugUmL,/ip4/127.0.0.1/tcp/15602/p2p/12D3KooWGdr8M5KX8KuKaXSiKfHJstdVnRkadYmupF7tFk2HrRoA,/ip4/127.0.0.1/tcp/15603/p2p/12D3KooWC7uE9w3RN4Vh1FJAZa8SbE8yMWR6wCVBajcWpyWguV73"
    secrets:
      - hornet.config.json
    volumes:
    - ./snapshots:/tmp/snapshots
    ports:
      - "8041:8081/tcp" # dashboard
      - "14465:14265/tcp" # REST-API
    networks:
      - shimmer
  peer_master5:
    image: hornet-ebsi
    stop_grace_period: 1m
    environment:
      - COO_PRV_KEYS=651941eddb3e68cb1f6ef4ef5b04625dcf5c70de1fdc4b1c9eadb2c219c074e0ed3c3f1a319ff4e909cf2771d79fece0ac9bd9fd2ee49ea6c0885c9cb3b1248c,0e324c6ff069f31890d496e9004636fd73d8e8b5bea08ec58a4178ca85462325f6752f5f46a53364e2ee9c4d662d762a81efd51010282a75cd6bd03f28ef349c
      - FAUCET_PRV_KEY=52d23081a626b1eca34b63f1eaeeafcbd66bf545635befc12cd0f19926efefb031f176dadf38cdec0eadd1d571394be78f0bbee3ed594316678dffc162a095cb
    command: >
      --config=/run/secrets/hornet.config.json
      --cooBootstrap
      --cooStartIndex=0
      --protocol.networkID="private_tangle1"
      --restAPI.bindAddress="0.0.0.0:14265"
      --dashboard.bindAddress="0.0.0.0:8081"
      --db.path="privatedb"
      --node.disablePlugins="Autopeering"
      --node.enablePlugins="Spammer,Coordinator,MQTT,Debug,Prometheus,Faucet"
      --snapshots.fullPath=/tmp/snapshots/private_tangle5/full_snapshot.bin
      --snapshots.deltaPath="/tmp/snapshots/private_tangle5/delta_snapshot.bin"
      --p2p.bindMultiAddresses="/ip4/127.0.0.1/tcp/15600"
      --profiling.bindAddress="127.0.0.1:6060"
      --prometheus.bindAddress="localhost:9311"
      --prometheus.fileServiceDiscovery.target="localhost:9311"
      --mqtt.bindAddress="localhost:1883"
      --p2p.db.path="p2pstore"
      --p2p.identityPrivateKey="1f46fad4f538a031d4f87f490f6bca4319dfd0307636a5759a22b5e8874bd608f9156ba976a12918c16a481c38c88a7b5351b769adc30390e93b6c0a63b09b79"
      --p2p.peers="/ip4/127.0.0.1/tcp/15601/p2p/12D3KooWCKwcTWevoRKa2kEBputeGASvEBuDfRDSbe8t1DWugUmL,/ip4/127.0.0.1/tcp/15602/p2p/12D3KooWGdr8M5KX8KuKaXSiKfHJstdVnRkadYmupF7tFk2HrRoA,/ip4/127.0.0.1/tcp/15603/p2p/12D3KooWC7uE9w3RN4Vh1FJAZa8SbE8yMWR6wCVBajcWpyWguV73"
    secrets:
      - hornet.config.json
    volumes:
    - ./snapshots:/tmp/snapshots
    ports:
      - "8051:8081/tcp" # dashboard
      - "14565:14265/tcp" # REST-API
    networks:
      - shimmer
  # grafana:
  #   image: grafana/grafana:latest
  #   restart: unless-stopped
  #   profiles:
  #     - grafana
  #   environment:
  #     # path to provisioning definitions can only be defined as
  #     # environment variables for grafana within docker
  #     - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning
  #   networks:
  #     - shimmer
  #   ports:
  #     - "3000:3000"
  #   user: "104"
  #   volumes:
  #     - grafana-data-volume:/var/lib/grafana
  #     - ./grafana/provisioning:/var/lib/grafana/provisioning:ro
  #     - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
# Create our own network
networks:
  shimmer:
    driver: bridge
# Named Docker volumes for data persistence
# ./run.sh removes these on exit
# volumes:
  # shimmerdb:
  # peerdb:
  # grafana-data-volume:
# read only files to load in the containers that may be shared across containers
secrets:
  hornet.config.json:
    file: ${HORNET_CONFIG:-./config_private_tangle.json}
  prometheus.yml:
    file: ${PROMETHEUS_CONFIG:-./prometheus.yml}
