scrape_configs:
  - job_name: metrics
    scrape_interval: 5s
    static_configs:
      - targets:
          - goshimmer_root:9311
          - hornet_child1:9311
          - hornet_child2:9311
          - hornet_child3:9311
          - hornet_child4:9311
          - hornet_child5:9311
          - hornet_child6:9311
          - hornet_child7:9311
          - hornet_child8:9311
          - hornet_child9:9311
          - hornet_child10:9311
          - hornet_child11:9311
          - ethereum:9311
