scrape_configs:
  - job_name: metrics
    scrape_interval: 5s
    static_configs:
      - targets:
          - goshimmer_root:9311
          - hornet_child1:9311
          - hornet_child2:9311
          - hornet_child3:9311
          - hornet_child4:9311
          - hornet_child5:9311
          - hornet_child6:9311
          - hornet_child7:9311
          - hornet_child8:9311
          - hornet_child9:9311
          - hornet_child10:9311
          - hornet_child11:9311
          - hornet_child12:9311
          - hornet_child13:9311
          - hornet_child14:9311
          - hornet_child15:9311
          - hornet_child16:9311
          - hornet_child17:9311
          - hornet_child18:9311
          - hornet_child19:9311
          - hornet_child20:9311
          - hornet_child21:9311
          - hornet_child22:9311
          - ethereum:9311
